<?php
return [
    10 => 'Land Transportation Office - LTO',
    11 => 'Commision on Election',
    12 => 'Department of Foreign Affairs',
    13 => 'Professional Regulation Commission',
    14 => 'National Bureau of Investigation',
    15 => 'Philippine National Police',
    16 => 'Philippine Postal Corporation',
    17 => 'Barangay of ',
    18 => 'Department of Labor and Employment',
    19 => 'Department of Labor and Employment',
    20 => 'N/A FOR FTI',
    21 => 'Philippine National Police',
    22 => 'Armed Forces of the Philippines',
    23 => 'Pag-IBIG Fund',
    24 => 'Local Government of ',
    25 => 'Department of Social Welfare and Development',
    26 => 'Bureau of Immigration',
    27 => 'Department of Trade and Industry',
    28 => 'Integrated Bar of the Philippines',
    29 => 'Philippine National Police',
    30 => 'Specific Government Instution',
    31 => 'N/A FOR FTI',
    32 => 'Philippine Statistics Authority',
    33 => 'N/A FOR FTI',
    34 => 'Specific Government Institution',
    35 => 'N/A FOR FTI',
    36 => 'BANKS (Name of Banks)',
    37 => 'N/A FOR FTI',
    38 => 'N/A FOR FTI',
    39 => 'Bureau of Immigration',
];
